<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Article;
use App\Models\Admin;
use Carbon\Carbon;
use Illuminate\Support\Str;

class ArticleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = Admin::first();
        
        if (!$admin) {
            $this->command->warn('No admin found. Please run AdminSeeder first.');
            return;
        }

        $articles = [
            // Breaking News (from The Star Malaysia)
            [
                'title' => 'Nearly 800,000 in Johor hit by water cuts due to Sg Johor pollution',
                'excerpt' => 'Massive water supply disruption affects hundreds of thousands of residents in Johor due to river pollution.',
                'content' => 'Hundreds of thousands of residents in Johor are experiencing water supply disruptions after pollution was detected in Sungai Johor. The affected areas span multiple districts, with authorities working around the clock to restore normal water supply. Environmental agencies are investigating the source of the contamination.',
                'slug' => Str::slug('Nearly 800,000 in Johor hit by water cuts due to Sg Johor pollution'),
                'featured_image' => 'https://placehold.co/1200x169/be185d/FFFFFF?text=Johor+Water+Cuts',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_BREAKING,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(2),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Selangor to decide soon on stalled WCE section involving 19 Kg Jawa residents, says MB',
                'excerpt' => 'Selangor state government to make decision on West Coast Expressway section affecting Kampung Jawa residents.',
                'content' => 'The Selangor state government is expected to make a decision soon regarding a stalled section of the West Coast Expressway (WCE) that involves 19 residents from Kampung Jawa. The Mentri Besar has assured that the matter will be resolved promptly.',
                'slug' => Str::slug('Selangor to decide soon on stalled WCE section involving 19 Kg Jawa residents'),
                'featured_image' => 'https://placehold.co/1200x169/059669/FFFFFF?text=Selangor+WCE',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_BREAKING,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => now()->subHours(3),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Digital transformation, AI at helm of APEC meet; Malaysia highlights moral, environmental risks',
                'excerpt' => 'Malaysia emphasizes the importance of ethical considerations in digital transformation and AI adoption during APEC summit.',
                'content' => 'At the APEC summit, Malaysia has taken a leading role in highlighting the moral and environmental risks associated with digital transformation and artificial intelligence. The country stressed the need for responsible AI deployment that considers ethical implications and environmental sustainability.',
                'slug' => Str::slug('Digital transformation AI at helm of APEC meet Malaysia highlights moral environmental risks'),
                'featured_image' => 'https://placehold.co/1200x169/1d4ed8/FFFFFF?text=APEC+AI',
                'category' => Article::CATEGORY_TECH,
                'type' => Article::TYPE_BREAKING,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => now()->subHours(4),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Floods: Situation in Kedah improves, unchanged in Perak',
                'excerpt' => 'Flood situation shows improvement in Kedah while remaining stable in Perak state.',
                'content' => 'Recent reports indicate that the flood situation in Kedah has shown signs of improvement, with water levels receding in affected areas. Meanwhile, the situation in Perak remains unchanged, with authorities continuing to monitor developments closely.',
                'slug' => Str::slug('Floods Situation in Kedah improves unchanged in Perak'),
                'featured_image' => 'https://placehold.co/1200x169/047857/FFFFFF?text=Floods',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_BREAKING,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => now()->subHours(5),
                'admin_id' => $admin->id,
            ],
            
            // Featured Articles (from The Star Malaysia)
            [
                'title' => 'Malaysia hands on Asean baton after landmark year of sustainable diplomacy',
                'excerpt' => 'Malaysia completes its Asean chairmanship with a focus on sustainable diplomacy and regional cooperation.',
                'content' => 'Every time Malaysia chairs Asean - once every decade - it leaves a clear imprint on the region\'s history. This year has been no exception, with the country focusing on sustainable diplomacy and strengthening regional ties. The landmark year has seen significant progress in various areas of cooperation.',
                'slug' => Str::slug('Malaysia hands on Asean baton after landmark year of sustainable diplomacy'),
                'featured_image' => 'https://placehold.co/1200x169/be185d/FFFFFF?text=Asean+Diplomacy',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_FEATURED,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 8,
                'is_published' => true,
                'published_at' => now()->subHours(2),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Asia-Pacific leaders wrap up Apec summit after Trump and Xi agreement on trade truce',
                'excerpt' => 'APEC summit concludes with major trade agreement between US and China leaders.',
                'content' => 'The Asia-Pacific Economic Cooperation summit concluded with a significant trade truce agreement between US President Trump and Chinese leader Xi Jinping. The agreement has been hailed as a breakthrough in US-China relations and is expected to have positive impacts on regional trade.',
                'slug' => Str::slug('Asia-Pacific leaders wrap up Apec summit after Trump and Xi agreement on trade truce'),
                'featured_image' => 'https://placehold.co/1200x169/1d4ed8/FFFFFF?text=APEC+Summit',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_FEATURED,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 7,
                'is_published' => true,
                'published_at' => now()->subHours(2),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'One year not enough, continuity essential to build sustainable legacy for Asean, says Defence Minister',
                'excerpt' => 'Defence Minister emphasizes the need for continuity beyond the one-year Asean chairmanship period.',
                'content' => 'Defence Minister Khaled Nordin has stressed that one year of Asean chairmanship is not sufficient, and continuity is essential to build a sustainable legacy for the regional organization. He highlighted the importance of maintaining momentum in various initiatives started during Malaysia\'s tenure.',
                'slug' => Str::slug('One year not enough continuity essential to build sustainable legacy for Asean says Defence Minister'),
                'featured_image' => 'https://placehold.co/1200x169/059669/FFFFFF?text=Asean+Legacy',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_FEATURED,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => now()->subHours(1),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Johor to produce over three million litres of fresh milk next year',
                'excerpt' => 'Johor state announces plans to significantly increase local milk production capacity.',
                'content' => 'Johor is set to produce over three million litres of fresh milk next year, marking a significant milestone in the state\'s agricultural sector. The announcement was made as part of the state\'s efforts to boost local food production and reduce dependency on imports.',
                'slug' => Str::slug('Johor to produce over three million litres of fresh milk next year'),
                'featured_image' => 'https://placehold.co/1200x169/b45309/FFFFFF?text=Johor+Milk',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_FEATURED,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(1),
                'admin_id' => $admin->id,
            ],
            
            // Regular Articles for grid (from The Star Malaysia)
            [
                'title' => 'Rafizi unveils social enterprise model to lower business barriers for youth',
                'excerpt' => 'Economy Minister introduces new social enterprise framework to help young entrepreneurs.',
                'content' => 'Economy Minister Rafizi Ramli has unveiled a new social enterprise model designed to lower barriers for young people entering business. The initiative aims to provide support and resources to help youth establish successful enterprises while addressing social challenges.',
                'slug' => Str::slug('Rafizi unveils social enterprise model to lower business barriers for youth'),
                'featured_image' => 'https://placehold.co/600x400/334155/FFFFFF?text=Social+Enterprise',
                'category' => Article::CATEGORY_BUSINESS,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(1),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Syed Saddiq powers through Ironman Malaysia to beat 13-hour target',
                'excerpt' => 'Former youth and sports minister completes grueling Ironman triathlon ahead of schedule.',
                'content' => 'Syed Saddiq Syed Abdul Rahman has successfully completed the Ironman Malaysia competition, finishing ahead of his 13-hour target. The former youth and sports minister demonstrated remarkable endurance throughout the challenging triathlon event.',
                'slug' => Str::slug('Syed Saddiq powers through Ironman Malaysia to beat 13-hour target'),
                'featured_image' => 'https://placehold.co/600x400/6d28d9/FFFFFF?text=Ironman',
                'category' => Article::CATEGORY_SPORTS,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(3),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Lenggeng sewage pit tragedy ruled accidental, cops say NFA',
                'excerpt' => 'Police confirm no further action after investigation into Lenggeng sewage pit incident.',
                'content' => 'The tragic incident at a sewage pit in Lenggeng has been ruled as accidental following police investigation. Authorities have confirmed that no further action (NFA) will be taken, as the incident was determined to be an unfortunate accident.',
                'slug' => Str::slug('Lenggeng sewage pit tragedy ruled accidental cops say NFA'),
                'featured_image' => 'https://placehold.co/600x400/b45309/FFFFFF?text=Lenggeng',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => now()->subHours(4),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Aerobic exercises the best for knee osteoarthritis',
                'excerpt' => 'New research shows aerobic exercises provide the most benefit for knee osteoarthritis patients.',
                'content' => 'Recent medical research has revealed that aerobic exercises are the most effective form of treatment for individuals suffering from knee osteoarthritis. The study highlights the importance of regular physical activity in managing the condition.',
                'slug' => Str::slug('Aerobic exercises the best for knee osteoarthritis'),
                'featured_image' => 'https://placehold.co/600x400/047857/FFFFFF?text=Wellness',
                'category' => Article::CATEGORY_HEALTH,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(6),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Former Sukau assemblyman joins Warisan, cites wave of change',
                'excerpt' => 'Ex-Sukau assemblyman announces switch to Warisan party, referencing political changes.',
                'content' => 'The former assemblyman for Sukau has officially joined the Warisan party, citing a "wave of change" in the political landscape. The move is seen as part of ongoing political realignments in Sabah.',
                'slug' => Str::slug('Former Sukau assemblyman joins Warisan cites wave of change'),
                'featured_image' => 'https://placehold.co/600x400/b45309/FFFFFF?text=Sabah+Politics',
                'category' => Article::CATEGORY_POLITICS,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(7),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Working hand in hand: Malaysia hunts seven suspects after Singapore busts Cambodia scam ring',
                'excerpt' => 'Malaysian authorities collaborate with Singapore to track down suspects linked to Cambodia-based scam operation.',
                'content' => 'Malaysia is working closely with Singaporean authorities to track down seven suspects following Singapore\'s successful bust of a Cambodia-based scam ring. The cross-border cooperation highlights the importance of regional collaboration in combating cybercrime.',
                'slug' => Str::slug('Working hand in hand Malaysia hunts seven suspects after Singapore busts Cambodia scam ring'),
                'featured_image' => 'https://placehold.co/600x400/1e40af/FFFFFF?text=Cybercrime',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => now()->subHours(8),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Crowns, beauty, fried chicken: Korean culture meets diplomacy at Apec',
                'excerpt' => 'Korean cultural elements showcased at APEC summit, blending tradition with modern diplomacy.',
                'content' => 'The APEC summit featured a unique blend of Korean culture and diplomacy, with elements ranging from traditional crowns to modern beauty products and even fried chicken. The cultural showcase highlighted South Korea\'s soft power approach to international relations.',
                'slug' => Str::slug('Crowns beauty fried chicken Korean culture meets diplomacy at Apec'),
                'featured_image' => 'https://placehold.co/600x400/6d28d9/FFFFFF?text=Korean+Culture',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(3),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "Is China's new Type 076 drone carrier starting key catapult test?",
                'excerpt' => 'Reports suggest China\'s latest naval vessel may be undergoing critical testing phases.',
                'content' => 'Military analysts are watching closely as China\'s new Type 076 drone carrier appears to be entering a key phase of catapult testing. The advanced naval vessel represents a significant development in China\'s military capabilities.',
                'slug' => Str::slug('Is Chinas new Type 076 drone carrier starting key catapult test'),
                'featured_image' => 'https://placehold.co/600x400/1e40af/FFFFFF?text=China+Military',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 7,
                'is_published' => true,
                'published_at' => now()->subHours(10),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "Asean spirit shines at APEC, says Anwar as China's Xi among world leaders to offer congratulations",
                'excerpt' => 'Prime Minister Anwar highlights Asean unity at APEC as world leaders congratulate Malaysia.',
                'content' => 'Prime Minister Datuk Seri Anwar Ibrahim has highlighted that the Asean spirit shone brightly at the APEC summit, with China\'s President Xi Jinping among world leaders offering congratulations to Malaysia. The recognition underscores Malaysia\'s successful leadership in regional diplomacy.',
                'slug' => Str::slug('Asean spirit shines at APEC says Anwar as Chinas Xi among world leaders to offer congratulations'),
                'featured_image' => 'https://placehold.co/600x400/be185d/FFFFFF?text=Asean+APEC',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => now()->subHours(2),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'US offer of assistance to Asean must be based on ADMM framework',
                'excerpt' => 'Regional security framework must guide US assistance offers to Asean nations.',
                'content' => 'Any offer of assistance from the United States to Asean must be structured within the Asean Defence Ministers\' Meeting (ADMM) framework, ensuring alignment with regional security priorities and protocols established by member nations.',
                'slug' => Str::slug('US offer of assistance to Asean must be based on ADMM framework'),
                'featured_image' => 'https://placehold.co/600x400/b45309/FFFFFF?text=US+Asean',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(4),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "Asean Defence Ministers' forum strengthens regional bloc's voice on global security, says Khaled",
                'excerpt' => 'Defence Minister emphasizes the importance of Asean unity in global security discussions.',
                'content' => 'Defence Minister Datuk Seri Mohamed Khaled Nordin has emphasized that the Asean Defence Ministers\' forum significantly strengthens the regional bloc\'s collective voice on matters of global security, highlighting the importance of regional solidarity.',
                'slug' => Str::slug('Asean Defence Ministers forum strengthens regional blocs voice on global security says Khaled'),
                'featured_image' => 'https://placehold.co/600x400/059669/FFFFFF?text=Asean+Defence',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(3),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Philippines to maintain Asean engagement with Myanmar under chairmanship, says President Marcos',
                'excerpt' => 'Philippines commits to continued Asean engagement with Myanmar during its chairmanship.',
                'content' => 'Philippine President Ferdinand Marcos Jr. has confirmed that the Philippines will maintain Asean engagement with Myanmar during its upcoming chairmanship period, demonstrating the bloc\'s continued commitment to diplomatic engagement.',
                'slug' => Str::slug('Philippines to maintain Asean engagement with Myanmar under chairmanship says President Marcos'),
                'featured_image' => 'https://placehold.co/600x400/6d28d9/FFFFFF?text=Philippines+Myanmar',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(5),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'QuickCheck: Is it true that people used to eat Egyptian mummies?',
                'excerpt' => 'Fact-checking the historical claim about consumption of Egyptian mummies.',
                'content' => 'An investigation into the historical claim that people used to consume Egyptian mummies. This True or Not segment examines the veracity of this unusual historical practice and explores the context behind such claims.',
                'slug' => Str::slug('QuickCheck Is it true that people used to eat Egyptian mummies'),
                'featured_image' => 'https://placehold.co/600x400/047857/FFFFFF?text=Fact+Check',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => now()->subHours(6),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'US and Cambodia revive defence drills after Asean nation agrees to Trump-backed peace deal',
                'excerpt' => 'Defence cooperation resumes between US and Cambodia following peace agreement.',
                'content' => 'The United States and Cambodia have revived their defence drills after the Asean nation agreed to a peace deal backed by former President Donald Trump. The resumption of military cooperation marks a significant step in bilateral relations.',
                'slug' => Str::slug('US and Cambodia revive defence drills after Asean nation agrees to Trump-backed peace deal'),
                'featured_image' => 'https://placehold.co/600x400/b45309/FFFFFF?text=US+Cambodia',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => now()->subHours(3),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "'In for a good swing' Kelly Tan leads the local charge and is fired up to finish on a high at Maybank Championship",
                'excerpt' => 'Malaysian golfer Kelly Tan leads local competitors at Maybank Championship.',
                'content' => 'Malaysian professional golfer Kelly Tan is leading the local charge at the Maybank Championship and is determined to finish the tournament on a high note. The tournament has drawn international attention with local fans rallying behind Tan\'s performance.',
                'slug' => Str::slug('In for a good swing Kelly Tan leads the local charge and is fired up to finish on a high at Maybank Championship'),
                'featured_image' => 'https://placehold.co/600x400/059669/FFFFFF?text=Golf',
                'category' => Article::CATEGORY_SPORTS,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(7),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "'The Beatles come alive'; Aimee Lou Wood, Saoirse Ronan confirmed to star in all-time legendary group's biopic",
                'excerpt' => 'Acclaimed actors Aimee Lou Wood and Saoirse Ronan join the cast of The Beatles biopic.',
                'content' => 'The highly anticipated biopic about legendary band The Beatles has confirmed that Aimee Lou Wood and Saoirse Ronan will star in the film. The casting announcement has generated significant excitement among fans of both the band and the talented actors.',
                'slug' => Str::slug('The Beatles come alive Aimee Lou Wood Saoirse Ronan confirmed to star in all-time legendary groups biopic'),
                'featured_image' => 'https://placehold.co/600x400/6d28d9/FFFFFF?text=Beatles',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(8),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'US Secretary of War advocates for prudent nuclear testing',
                'excerpt' => 'US defence official calls for careful consideration of nuclear testing protocols.',
                'content' => 'The US Secretary of War has advocated for prudent nuclear testing, emphasizing the need for careful consideration and adherence to international protocols. The statement comes amid ongoing global discussions about nuclear weapons policy.',
                'slug' => Str::slug('US Secretary of War advocates for prudent nuclear testing'),
                'featured_image' => 'https://placehold.co/600x400/b45309/FFFFFF?text=Nuclear',
                'category' => Article::CATEGORY_WORLD,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => now()->subHours(9),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Incorporating AI to battle floods',
                'excerpt' => 'Technology solutions using artificial intelligence to improve flood management systems.',
                'content' => 'Authorities are exploring ways to incorporate artificial intelligence technology to better predict, manage, and respond to flooding incidents. The innovative approach aims to improve early warning systems and enhance disaster response capabilities.',
                'slug' => Str::slug('Incorporating AI to battle floods'),
                'featured_image' => 'https://placehold.co/600x400/1d4ed8/FFFFFF?text=AI+Floods',
                'category' => Article::CATEGORY_TECH,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(1),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Affordable housing woes revisited',
                'excerpt' => 'Ongoing challenges in Malaysia\'s affordable housing sector.',
                'content' => 'The persistent challenges facing Malaysia\'s affordable housing sector are being revisited, with stakeholders examining new approaches to address accessibility and affordability issues for middle and lower-income families.',
                'slug' => Str::slug('Affordable housing woes revisited'),
                'featured_image' => 'https://placehold.co/600x400/334155/FFFFFF?text=Housing',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(11),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'The elevator debate',
                'excerpt' => 'Discussions continue about elevator requirements in residential buildings.',
                'content' => 'The ongoing debate about elevator requirements in residential buildings has resurfaced, with stakeholders weighing the benefits of accessibility against construction and maintenance costs. The discussion touches on urban planning and inclusive design principles.',
                'slug' => Str::slug('The elevator debate'),
                'featured_image' => 'https://placehold.co/600x400/64748b/FFFFFF?text=Elevator',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => now()->subHours(1),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "Cricket-History at stake as India and South Africa battle for maiden World Cup triumph",
                'excerpt' => 'Cricket World Cup final features India and South Africa competing for first championship.',
                'content' => 'History is on the line as cricket powerhouses India and South Africa prepare to battle for their maiden World Cup triumph. Both teams are seeking their first championship in what promises to be a thrilling final match.',
                'slug' => Str::slug('Cricket-History at stake as India and South Africa battle for maiden World Cup triumph'),
                'featured_image' => 'https://placehold.co/600x400/6d28d9/FFFFFF?text=Cricket',
                'category' => Article::CATEGORY_SPORTS,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => now()->subHours(1),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "Soccer-Egypt's Zamalek sack coach Ferrera after four-game winless run",
                'excerpt' => 'Egyptian football club terminates coach following disappointing results.',
                'content' => 'Egyptian football club Zamalek has sacked coach Ferrera following a four-game winless run. The decision comes as the club seeks to improve its performance and results in upcoming matches.',
                'slug' => Str::slug('Soccer-Egypts Zamalek sack coach Ferrera after four-game winless run'),
                'featured_image' => 'https://placehold.co/600x400/b45309/FFFFFF?text=Soccer',
                'category' => Article::CATEGORY_SPORTS,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => now()->subHours(2),
                'admin_id' => $admin->id,
            ],
            [
                'title' => "Malaysia's average household health insurance spending surges 283%",
                'excerpt' => 'Significant increase in household spending on health insurance revealed in study.',
                'content' => 'A comprehensive study has revealed that Malaysia\'s average household health insurance spending has surged by 283%, reflecting growing awareness of healthcare costs and the importance of insurance coverage. The trend highlights changing attitudes toward health security.',
                'slug' => Str::slug('Malaysias average household health insurance spending surges 283'),
                'featured_image' => 'https://placehold.co/600x400/047857/FFFFFF?text=Health+Insurance',
                'category' => Article::CATEGORY_HEALTH,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 5,
                'is_published' => true,
                'published_at' => now()->subHours(12),
                'admin_id' => $admin->id,
            ],
            
            // Articles for "HEARD THE NEWS?" section (latest 3)
            [
                'title' => 'Nearly 800,000 in Johor hit by water cuts due to Sg Johor pollution',
                'excerpt' => 'Massive water supply disruption affects hundreds of thousands of residents in Johor.',
                'content' => 'Hundreds of thousands of residents in Johor are experiencing water supply disruptions after pollution was detected in Sungai Johor. The affected areas span multiple districts, with authorities working around the clock to restore normal water supply.',
                'slug' => Str::slug('Nearly 800,000 in Johor hit by water cuts due to Sg Johor pollution heard'),
                'featured_image' => 'https://placehold.co/400x250/334155/FFFFFF?text=Johor+Water',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 4,
                'is_published' => true,
                'published_at' => Carbon::parse('2025-10-31 06:50:00'),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Selangor to decide soon on stalled WCE section involving 19 Kg Jawa residents, says MB',
                'excerpt' => 'Decision expected soon on West Coast Expressway section affecting Kampung Jawa.',
                'content' => 'The Selangor state government is expected to make a decision soon regarding a stalled section of the West Coast Expressway (WCE) that involves 19 residents from Kampung Jawa.',
                'slug' => Str::slug('Selangor to decide soon on stalled WCE section involving 19 Kg Jawa residents heard'),
                'featured_image' => 'https://placehold.co/400x250/059669/FFFFFF?text=Selangor+WCE',
                'category' => Article::CATEGORY_NATION,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 3,
                'is_published' => true,
                'published_at' => Carbon::parse('2025-10-31 06:40:00'),
                'admin_id' => $admin->id,
            ],
            [
                'title' => 'Digital transformation, AI at helm of APEC meet; Malaysia highlights moral, environmental risks',
                'excerpt' => 'Malaysia emphasizes ethical considerations in digital transformation during APEC.',
                'content' => 'At the APEC summit, Malaysia has taken a leading role in highlighting the moral and environmental risks associated with digital transformation and artificial intelligence.',
                'slug' => Str::slug('Digital transformation AI at helm of APEC meet Malaysia highlights moral environmental risks heard'),
                'featured_image' => 'https://placehold.co/400x250/b45309/FFFFFF?text=APEC+AI',
                'category' => Article::CATEGORY_TECH,
                'type' => Article::TYPE_NORMAL,
                'source' => 'THE STAR',
                'source_logo' => 'https://placehold.co/40x40/dc2626/FFFFFF?text=STAR',
                'reading_time' => 6,
                'is_published' => true,
                'published_at' => Carbon::parse('2025-10-31 06:31:00'),
                'admin_id' => $admin->id,
            ],
        ];

        $createdCount = 0;
        $skippedCount = 0;

        foreach ($articles as $article) {
            // Check if article already exists by slug (unique identifier)
            $existingArticle = Article::where('slug', $article['slug'])->first();
            
            if ($existingArticle) {
                $skippedCount++;
                continue; // Skip if already exists
            }

            Article::create($article);
            $createdCount++;
        }

        $this->command->info("Article seeder completed: {$createdCount} created, {$skippedCount} skipped.");
    }
}

